services:
  # -------- MySQL (NO external volume) --------
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ciumbe@254
      MYSQL_DATABASE: classicmodels
      MYSQL_USER: shopuser
      MYSQL_PASSWORD: shoppass
    ports:
      - "3307:3306"        # host 3307 → container 3306
    networks:
      - app-network
    # ⬆️  Hakuna entry ya "volumes:" – data iko ndani ya layer ya container

  # -------- Spring‑Boot Backend --------
  backend:
    build:
      context: ./backend      # path ya Dockerfile yako
    container_name: backend
    depends_on:
      - mysql
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/classicmodels
      SPRING_DATASOURCE_USERNAME: shopuser
      SPRING_DATASOURCE_PASSWORD: shoppass
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    networks:
      - app-network

  # ---- React Frontend (uncomment ukishai‐dockerise) ----
  # frontend:
  #   build:
  #     context: ./frontend
  #   container_name: frontend
  #   depends_on:
  #     - backend
  #   restart: always
  #   ports:
  #     - "5173:80"
  #   networks:
  #     - app-network

networks:
  app-network:
